spring:
  application:
    name: springcloud-config-test
  profiles:
    active: test-update
  cloud:
    config:
      info: master branch,springcloud-config/config-dev.yml version=7
      

#模拟运维修改了配置O(∩_∩)O哈哈~
